// Generated by ts-to-zod
import { z } from "zod";

const bidderDtoSchema = z.any();

export const bidPackageDtoSchema = z.object({
    type: z.union([z.literal("TV"), z.literal("TT"), z.literal("TC")]),
    projectOwner: z.string(),
    bidPackageName: z.string(),
    shortDescription: z.string(),
    cost: z.number(),
    costString: z.string(),
    bidderSelectionTime: z.string(),
    bidderSelectionMethod: z.string(),
    successfulBidder: bidderDtoSchema.optional(),
    upTo: z.string(),
    isCompleted: z.boolean()
});
