// Generated by ts-to-zod
import { z } from "zod";

export const bidderDtoSchema = z.object({
    name: z.string(),
    legalRepresentative: z.object({
        name: z.string(),
        position: z.string()
    }),
    address: z.string(),
    phone: z.string(),
    email: z.string(),
    taxCode: z.string(),
    bankAccount: z.object({
        accountNumber: z.string(),
        bankName: z.string(),
        branch: z.string()
    })
});
