// Generated by ts-to-zod
import { z } from "zod";

export const nestedAdministrativeDocumentDtoSchema = z.object({
    id: z.string().optional(),
    no: z.string(),
    level: z.string(),
    date: z.string()
});
