import type { Construction } from "@/types";

export async function getConstructions_mock(): Promise<Construction[]> {
  return [
    {
      id: "construction-1",
      decisions: [
        {
          id: "dec-1",
          no: "QD-001",
          level: "Tỉnh",
          date: "2024-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "KH_LCNT",

          submission: {
            id: "sub-1",
            no: "SUB-001",
            level: "Sở",
            date: "2024-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,

            construction_infor_snapshot: {
              id: "1",
              name: "Sửa chữa Trường Tiểu học A",
              source_of_funds: "Ngân sách tỉnh",
              impl_start_date: "2024-02-01",
              impl_end_date: "2024-08-01",
              existing_condition_of_the_structure: "Công trình xuống cấp",
              repair_scope:
                "Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,  Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,",
              est_cost: 1900000000,
              est_cost_str: "1.9 tỷ",

              bid_package_snapshots: [
                {
                  id: "1",
                  type: "TV",
                  project_owner: "UBND Tỉnh",
                  name: "Tư vấn thiết kế",
                  short_desc: "Thiết kế bản vẽ",
                  bidder_selection_time: "2024-02",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "30 ngày",
                  is_completed: false,
                  est_cost: 180000000,
                  est_cost_str: "180 triệu",
                },
                {
                  id: "2",
                  type: "TC",
                  project_owner: "UBND Tỉnh",
                  name: "Thi công sửa chữa",
                  short_desc: "Thi công công trình",
                  bidder_selection_time: "2024-03",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "120 ngày",
                  is_completed: false,
                  est_cost: 1400000000,
                  est_cost_str: "1.4 tỷ",
                },
              ],
            },
          },
        },
        {
          id: "dec-1",
          no: "02/QĐ-TTMN",
          level: "Tỉnh",
          date: "2026-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "KH_LCNT",

          submission: {
            id: "sub-1",
            no: "02/TTr-LCQ",
            level: "Sở",
            date: "2026-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,
          },
        },
        {
          id: "dec-1",
          no: "02/QĐ-TTMN",
          level: "Tỉnh",
          date: "2026-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "BCKTKT",

          submission: {
            id: "sub-1",
            no: "02/TTr-LCQ",
            level: "Sở",
            date: "2026-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,
            construction_infor_snapshot: {
              id: "1",
              name: "Sửa chữa Trường Tiểu học A",
              source_of_funds: "Ngân sách tỉnh",
              impl_start_date: "2024-02-01",
              impl_end_date: "2024-08-01",
              existing_condition_of_the_structure: "Công trình xuống cấp",
              repair_scope:
                "Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,  Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,",
              est_cost: 1900000000,
              est_cost_str: "1.9 tỷ",

              bid_package_snapshots: [
                {
                  id: "1",
                  type: "TV",
                  project_owner: "UBND Tỉnh",
                  name: "Tư vấn thiết kế",
                  short_desc: "Thiết kế bản vẽ",
                  bidder_selection_time: "2024-02",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "30 ngày",
                  is_completed: false,
                  est_cost: 180000000,
                  est_cost_str: "180 triệu",
                },
                {
                  id: "2",
                  type: "TC",
                  project_owner: "UBND Tỉnh",
                  name: "Thi công sửa chữa",
                  short_desc: "Thi công công trình",
                  bidder_selection_time: "2024-03",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "120 ngày",
                  is_completed: false,
                  est_cost: 1400000000,
                  est_cost_str: "1.4 tỷ",
                },
              ],
            },
          },
        },
      ],
    },
    {
      id: "construction-2",
      decisions: [
        {
          id: "dec-2",
          no: "QD-002",
          level: "Tỉnh",
          date: "2024-03-15",
          pursuant_to_dec_tct: null,
          pursuant_to_dec_ttmn: null,
          period: "KH_LCNT",

          submission: {
            id: "sub-2",
            no: "SUB-002",
            level: "Sở",
            date: "2024-03-10",
            is_change_construction_infor: false,
            pursuant_to_dec_tct: null,
            pursuant_to_dec_ttmn: null,

            construction_infor_snapshot: {
              id: "2",
              name: "Nâng cấp đường nội thị",
              source_of_funds: "Ngân sách thành phố",
              impl_start_date: "2024-04-01",
              impl_end_date: "2024-12-01",
              existing_condition_of_the_structure: "Đường hư hỏng",
              repair_scope: "Nâng cấp mặt đường",
              est_cost: 4800000000,
              est_cost_str: "4.8 tỷ",

              bid_package_snapshots: [
                {
                  id: "3",
                  type: "TV",
                  project_owner: "UBND TP",
                  name: "Tư vấn giám sát",
                  short_desc: "Giám sát thi công",
                  bidder_selection_time: "2024-04",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "6 tháng",
                  is_completed: false,
                  est_cost: 280000000,
                  est_cost_str: "280 triệu",
                },
                {
                  id: "4",
                  type: "TC",
                  project_owner: "UBND TP",
                  name: "Thi công nâng cấp",
                  short_desc: "Thi công đường",
                  bidder_selection_time: "2024-05",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "8 tháng",
                  is_completed: false,
                  est_cost: 4000000000,
                  est_cost_str: "4 tỷ",
                },
              ],
            },
          },
        },
        {
          id: "dec-3",
          no: "QD-003",
          level: "Tỉnh",
          date: "2024-03-15",
          pursuant_to_dec_tct: null,
          pursuant_to_dec_ttmn: null,
          period: "KH_LCNT",

          submission: {
            id: "sub-3",
            no: "SUB-003",
            level: "Sở",
            date: "2024-03-10",
            is_change_construction_infor: false,
            pursuant_to_dec_tct: null,
            pursuant_to_dec_ttmn: null,

            construction_infor_snapshot: {
              id: "2",
              name: "Nâng cấp đường nội thị",
              source_of_funds: "Ngân sách thành phố",
              impl_start_date: "2024-04-01",
              impl_end_date: "2024-12-01",
              existing_condition_of_the_structure: "Đường hư hỏng",
              repair_scope: "Nâng cấp mặt đường",
              est_cost: 4800000000,
              est_cost_str: "4.8 tỷ",

              bid_package_snapshots: [
                {
                  id: "3",
                  type: "TV",
                  project_owner: "UBND TP",
                  name: "Tư vấn giám sát",
                  short_desc: "Giám sát thi công",
                  bidder_selection_time: "2024-04",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "6 tháng",
                  is_completed: false,
                  est_cost: 280000000,
                  est_cost_str: "280 triệu",
                },
                {
                  id: "4",
                  type: "TC",
                  project_owner: "UBND TP",
                  name: "Thi công nâng cấp",
                  short_desc: "Thi công đường",
                  bidder_selection_time: "2024-05",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "8 tháng",
                  is_completed: false,
                  est_cost: 4000000000,
                  est_cost_str: "4 tỷ",
                },
              ],
            },
          },
        },
      ],
    },
  ];
}
