import type { Construction } from "@/types";

export async function getConstructions(): Promise<Construction[]> {
  return [
    {
      id: "construction-1",
      decisions: [
        {
          id: "dec-1",
          no: "QD-001",
          level: "Tỉnh",
          date: "2024-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "TV",

          submission: {
            id: "sub-1",
            no: "SUB-001",
            level: "Sở",
            date: "2024-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,

            construction_infor_snapshot: {
              id: "1",
              name: "Sửa chữa Trường Tiểu học A",
              budget: 2000000000,
              budget_str: "2 tỷ",
              source_of_funds: "Ngân sách tỉnh",
              impl_start_date: "2024-02-01",
              impl_end_date: "2024-08-01",
              existing_condition_of_the_structure: "Công trình xuống cấp",
              repair_scope:
                "Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,  Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,",
              est_cost: 1900000000,
              est_cost_str: "1.9 tỷ",

              bid_package_snapshots: [
                {
                  id: "1",
                  type: "TV",
                  project_owner: "UBND Tỉnh",
                  bid_package_name: "Tư vấn thiết kế",
                  short_description: "Thiết kế bản vẽ",
                  budget: 200000000,
                  budget_str: "200 triệu",
                  bidder_selection_time: "2024-02",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "30 ngày",
                  is_completed: false,
                  est_cost: 180000000,
                  est_cost_str: "180 triệu",
                },
                {
                  id: "2",
                  type: "TC",
                  project_owner: "UBND Tỉnh",
                  bid_package_name: "Thi công sửa chữa",
                  short_description: "Thi công công trình",
                  budget: 1500000000,
                  budget_str: "1.5 tỷ",
                  bidder_selection_time: "2024-03",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "120 ngày",
                  is_completed: false,
                  est_cost: 1400000000,
                  est_cost_str: "1.4 tỷ",
                },
              ],
            },
          },
        },
        {
          id: "dec-1",
          no: "02/QĐ-TTMN",
          level: "Tỉnh",
          date: "2026-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "TT",

          submission: {
            id: "sub-1",
            no: "02/TTr-LCQ",
            level: "Sở",
            date: "2026-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,
          },
        },
        {
          id: "dec-1",
          no: "02/QĐ-TTMN",
          level: "Tỉnh",
          date: "2026-01-10",
          pursuant_to_dec_tct: {
            id: "dec-0",
            no: "001/QĐ-TCT",
            date: "2024-01-10",
          },
          pursuant_to_dec_ttmn: null,
          period: "BCKTKT",

          submission: {
            id: "sub-1",
            no: "02/TTr-LCQ",
            level: "Sở",
            date: "2026-01-09",
            pursuant_to_dec_tct: {
              id: "dec-0",
              no: "001/QĐ-TCT",
              date: "2024-01-10",
            },
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,
            construction_infor_snapshot: {
              id: "1",
              name: "Sửa chữa Trường Tiểu học A",
              budget: 2000000000,
              budget_str: "2 tỷ",
              source_of_funds: "Ngân sách tỉnh",
              impl_start_date: "2024-02-01",
              impl_end_date: "2024-08-01",
              existing_condition_of_the_structure: "Công trình xuống cấp",
              repair_scope:
                "Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,  Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường, Sửa mái và tường,",
              est_cost: 1900000000,
              est_cost_str: "1.9 tỷ",

              bid_package_snapshots: [
                {
                  id: "1",
                  type: "TV",
                  project_owner: "UBND Tỉnh",
                  bid_package_name: "Tư vấn thiết kế",
                  short_description: "Thiết kế bản vẽ",
                  budget: 200000000,
                  budget_str: "200 triệu",
                  bidder_selection_time: "2024-02",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "30 ngày",
                  is_completed: false,
                  est_cost: 180000000,
                  est_cost_str: "180 triệu",
                },
                {
                  id: "2",
                  type: "TC",
                  project_owner: "UBND Tỉnh",
                  bid_package_name: "Thi công sửa chữa",
                  short_description: "Thi công công trình",
                  budget: 1500000000,
                  budget_str: "1.5 tỷ",
                  bidder_selection_time: "2024-03",
                  bidder_selection_method: "Đấu thầu rộng rãi",
                  successful_bidder_id: null,
                  duration: "120 ngày",
                  is_completed: false,
                  est_cost: 1400000000,
                  est_cost_str: "1.4 tỷ",
                },
              ],
            },
          },
        },
      ],
    },

    {
      id: "construction-2",
      decisions: [
        {
          id: "dec-2",
          no: "QD-002",
          level: "Tỉnh",
          date: "2024-03-15",
          pursuant_to_dec_tct: null,
          pursuant_to_dec_ttmn: null,
          period: "TT",

          submission: {
            id: "sub-2",
            no: "SUB-002",
            level: "Sở",
            date: "2024-03-10",
            pursuant_to_dec_tct: null,
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,

            construction_infor_snapshot: {
              id: "2",
              name: "Nâng cấp đường nội thị",
              budget: 5000000000,
              budget_str: "5 tỷ",
              source_of_funds: "Ngân sách thành phố",
              impl_start_date: "2024-04-01",
              impl_end_date: "2024-12-01",
              existing_condition_of_the_structure: "Đường hư hỏng",
              repair_scope: "Nâng cấp mặt đường",
              est_cost: 4800000000,
              est_cost_str: "4.8 tỷ",

              bid_package_snapshots: [
                {
                  id: "3",
                  type: "TV",
                  project_owner: "UBND TP",
                  bid_package_name: "Tư vấn giám sát",
                  short_description: "Giám sát thi công",
                  budget: 300000000,
                  budget_str: "300 triệu",
                  bidder_selection_time: "2024-04",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "6 tháng",
                  is_completed: false,
                  est_cost: 280000000,
                  est_cost_str: "280 triệu",
                },
                {
                  id: "4",
                  type: "TC",
                  project_owner: "UBND TP",
                  bid_package_name: "Thi công nâng cấp",
                  short_description: "Thi công đường",
                  budget: 4200000000,
                  budget_str: "4.2 tỷ",
                  bidder_selection_time: "2024-05",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "8 tháng",
                  is_completed: false,
                  est_cost: 4000000000,
                  est_cost_str: "4 tỷ",
                },
              ],
            },
          },
        },
      ],
    },

    {
      id: "construction-3",
      decisions: [
        {
          id: "dec-3",
          no: "QD-003",
          level: "Tỉnh",
          date: "2024-05-01",
          pursuant_to_dec_tct: null,
          pursuant_to_dec_ttmn: null,
          period: "TV",

          submission: {
            id: "sub-3",
            no: "SUB-003",
            level: "Sở",
            date: "2024-04-25",
            pursuant_to_dec_tct: null,
            pursuant_to_dec_ttmn: null,
            is_change_construction_infor: false,

            construction_infor_snapshot: {
              id: "3",
              name: "Cải tạo bệnh viện huyện",
              budget: 8000000000,
              budget_str: "8 tỷ",
              source_of_funds: "Ngân sách trung ương",
              impl_start_date: "2024-06-01",
              impl_end_date: "2025-01-01",
              existing_condition_of_the_structure: "Xuống cấp",
              repair_scope: "Sửa chữa toàn bộ",
              est_cost: 7600000000,
              est_cost_str: "7.6 tỷ",

              bid_package_snapshots: [
                {
                  id: "5",
                  type: "TV",
                  project_owner: "Sở Y tế",
                  bid_package_name: "Thiết kế cải tạo",
                  short_description: "Thiết kế bệnh viện",
                  budget: 500000000,
                  budget_str: "500 triệu",
                  bidder_selection_time: "2024-06",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "45 ngày",
                  is_completed: false,
                  est_cost: 450000000,
                  est_cost_str: "450 triệu",
                },
                {
                  id: "6",
                  type: "TC",
                  project_owner: "Sở Y tế",
                  bid_package_name: "Thi công cải tạo",
                  short_description: "Thi công bệnh viện",
                  budget: 6500000000,
                  budget_str: "6.5 tỷ",
                  bidder_selection_time: "2024-07",
                  bidder_selection_method: "Đấu thầu",
                  successful_bidder_id: null,
                  duration: "9 tháng",
                  is_completed: false,
                  est_cost: 6200000000,
                  est_cost_str: "6.2 tỷ",
                },
              ],
            },
          },
        },
      ],
    },
  ];
}
